### ISSUE TITLE
Add index.html to this repo

### ISSUE THREAD

**Issue by jhrcek** [opensolid/opensolid.github.io#1]
Discovering your packages (especially svg and geometry) just made my day :-)
However the link to GitHub https://opensolid.github.io/ (also linked from the description of this repo) leads to 404 page. I know I can go to example pages directly (like https://opensolid.github.io/examples/ConvexHull.html) but It would be nice to have an index linking to all the examples. Or are they linked from elsewhere, which I missed?

**Comment by ianmackenzie** [comment]
Hi @jhrcek, glad you're enjoying the packages! You're absolutely right that I should have a page that links to the various examples, although that will probably end up being part of a larger refactoring - I'm actually in the process right now of moving `opensolid/geometry` to [`ianmackenzie/elm-geometry`](https://github.com/ianmackenzie/elm-geometry) (in the spirit of the [literal names policy](https://discourse.elm-lang.org/t/literal-names-policy-i-e-how-to-name-packages/242/24)). So the contents of `opensolid.github.io` will probably end up being moved to `ianmackenzie.github.io/elm-geometry` or something like that. I've added a new issue on the `elm-geometry` repo (as you can see above!) to make sure this doesn't get forgotten =)

In the short term, what exactly do you mean by "the link to GitHub"? I've removed the link from description of this repo; was there another actual link somewhere that you followed that should be removed or changed?

**Comment by jhrcek** [comment]
> what exactly do you mean by "the link to GitHub"? 

Yes, I meant the one you removed. My "journey" discovering this issue was: 
read your [question](https://discourse.elm-lang.org/t/where-to-put-encoders-decoders-and-generators/711/14) on elm discourse, opened opensolid/geometry link there, got excited about the repo, so clicked the opensolid "organization" link to see if there are more repos like these, clicked the 2nd link opensolid.github.io and finally the link in its description. I'm not aware of any other links :)

**Comment by ianmackenzie** [comment]
OK, thanks! I'll close this issue in favor of the one on the `elm-geometry` repo then. Feel free to raise more issues if you run into anything, or message me on Slack if you have general comments/questions =)
